### ISSUE TITLE
✨ [Feat] 모임 관련 api 수정

### ISSUE THREAD

**Issue by catturtle123** [M0IM/BE#152]
## 📝 개요
- 모임 관련 api 수정

## ✔️ To-Do
- [x] 모임 가입 신청 확인하기 (신청한 사람이 확인 -> 삭제한 것을 추가) / 관련 테이블 추가
- [x] 가입 거절하기
- [x] 공지사항, 승인, 거절 시 fcm토큰 보내게금 추가
- [x] 모임장 위임 기능

## 👀 ETC
- 참고자료 등 기타 내용 작성
