### ISSUE TITLE
✨ [Feat] 유저 특정 날짜 일정 개수 조회 기능 구현

### ISSUE THREAD

**Issue by yewonahn** [M0IM/BE#158]
## 📝 개요
- 유저 특정 날짜 일정 개수 조회 기능 구현

## ✔️ To-Do
- [x] 유저 특정 날짜 일정 개수 조회 기능 구현
- [x] 일정 조회 DTO 작성자 id 추가
- [x] plan 엔티티에 writer 추가
- [x] 유저 관련 엔티티 정리
- [x] 모임 일정 생성 시, 작성자 유저 자동으로 참여 신청되던 로직에서 자동 참여 신청되지 않도록 변경
- [x] 일정 관련 에러 정리

## 👀 ETC
- 참고자료 등 기타 내용 작성
