### ISSUE TITLE
♻️ [Refactor] 게시글 관련 api 수정

### ISSUE THREAD

**Issue by catturtle123** [M0IM/BE#195]
## 📝 개요
- 게시글 관련 api 수정

## ✔️ To-Do
- [x] 차단, 삭제 구분 status 만들기
- [x] 게시글 type postType 넘겨주기
- [x] 공지 사항 읽을 사람 설정하기

## 👀 ETC
- 참고자료 등 기타 내용 작성
