### ISSUE TITLE
♻️ [Refactor] 모임 관련 api 수정

### ISSUE THREAD

**Issue by catturtle123** [M0IM/BE#210]
## 📝 개요
- 모임 관련 api 수정

## ✔️ To-Do
- [x] 게시물 조회 시 GLOBAL 제외
- [x] 모임 중 대표 이미지 리턴 값 추가
- [x] isJoin Loading 상태 추가
- [x] 읽을 사람 추가 및 읽을 사람 조회 기능
- [x] FCM 오류 해결
- [x] 신청 상태 확인, 모임 가입 멤버 search query 추가

## 👀 ETC
- 참고자료 등 기타 내용 작성
