### ISSUE TITLE
🐛 [Fix] 모임 관련 버그 해결

### ISSUE THREAD

**Issue by catturtle123** [M0IM/BE#222]
## 📝 개요
- 모임 관련 버그 해결

## ✔️ To-Do
- [x] 대댓글 차단처리 확인
- [x] 모임 멤버가입 조회 접근 역할 변경
- [x] /moims/what시 유저 모임 deleted 처리

## 👀 ETC
- 참고자료 등 기타 내용 작성
