### ISSUE TITLE
♻️ [Refactor] 모임 관련 수정

### ISSUE THREAD

**Issue by catturtle123** [M0IM/BE#236]
## 📝 개요
- 자세한 개요 작성

## ✔️ To-Do
- [x] 안 읽은 사람 요청
- [x] 게시물 리턴 시 writer id 리턴
- [x] 모임 신청자 0명 일 시 모임 제거
- [x] 가입 신청 상태 삭제 기능
- [x] 가입 신청 확인 시 삭제

## 👀 ETC
- 참고자료 등 기타 내용 작성
