### ISSUE TITLE
🐛 [Fix] 알림 전송 대상에 자신도 포함된 경우 처리

### ISSUE THREAD

**Issue by yewonahn** [M0IM/BE#285]
## 📝 개요
- 모임의 todo를 생성할 때, todo를 할당받을 assignee에 작성자 자신도 포함한 케이스에 대한 처리가 이루어지지 않았었습니다. 따라서 todo 생성 요청 시, todo 생성, userTodo 생성 및 알림 생성은 되지만, 작성자의 user 테이블에서 deviceId가 null 처리되는 버그가 발생했습니다. 따라서 이때 deviceId가 null이 되면서, 이후 요청이 들어올 때, @AuthUser에서 deviceId가 null인지 검증하는 과정에서 예외가 발생하게 되고, 해당 accessToken이 blackList에 등록되면서 이후 요청이 막히게 됐습니다. 따라서 버그를 해결하고자 알림 전송 대상에 유저 자신도 포함된 경우 처리를 추가합니다.

## ✔️ To-Do
- [x] todo 생성 로직에서 처리 추가
- [x] 일정 참여 로직에서 처리 추가
- [x] 일정 수정 로직에서 처리 추가
- [x] 일정 삭제 로직에서 처리 추가

## 👀 ETC
- 참고자료 등 기타 내용 작성
