### ISSUE TITLE
♻️ [Refactor] 모임 관련 api 수정

### ISSUE THREAD

**Issue by catturtle123** [M0IM/BE#303]
## 📝 개요
- 모임 관련 api 수정

## ✔️ To-Do
- [x] 모임 관련 카테고리 DTO
- [x] 모임 찾기 API
- [x] 내가 활동 중인 모임 확인 API

## 👀 ETC
- 참고자료 등 기타 내용 작성
