### ISSUE TITLE
📝 [Docs] Swagger 명세서 수정

### ISSUE THREAD

**Issue by catturtle123** [M0IM/BE#33]
## 📝 개요
- Swagger 명세서 수정

## ✔️ To-Do
- [x] 모임 관련 명세 수정
- [x] 모임 게시글 관련 명세 수정
- [x] 채팅 관련 명세 수정

## 👀 ETC
- 참고자료 등 기타 내용 작성
