### ISSUE TITLE
✨ [Feat] 유저 엔티티 성별, 거주지, 생년월일 필드 null 허용

### ISSUE THREAD

**Issue by yewonahn** [M0IM/BE#374]
## 📝 개요
- 배포 과정에서 특정 유저 정보 (성별, 거주지, 생년월일) 의 경우 개인 정보 보호 규정에 의해 선택 사항으로 두게되어 해당 정보들을 null을 허용하도록 변경합니다

## ✔️ To-Do
- [x] 유저 엔티티 성별, 거주지, 생년월일 필드 null 허용
- [x] Gender enum에 적용
- [x] 회원가입 로직에서 반영
- [x] (멀티 프로필 적용 전 ver) 유저 정보 수정 DTO에 반영
- [x] (멀티 프로필 적용 후 ver) 유저 기본 정보 수정 DTO에 반영

## 👀 ETC
- 참고자료 등 기타 내용 작성
