### ISSUE TITLE
✨ [Feat] 멀티 프로필 기능 수정

### ISSUE THREAD

**Issue by yewonahn** [M0IM/BE#398]
## 📝 개요
- 모임 가입 시, 개별 유저의 해당 모임에서의 프로필이 자동 생성되는 플로우로 멀티 프로필 기능 수정

## ✔️ To-Do
- [x] 기존 멀티 프로필 플로우에서 사용되던 API 정리
- [x] 기존 프로필 조회 관련 DTO 수정
- UserProfile 엔티티 삭제하면서, profileId, profileType 필드 제거 필요
- [ ] 프로필 관련 요청 uri profile -> profiles 변경 -> 프론트 확인 후 진행
- [ ] 다른 멤버 프로필 조회하는 케이스
- 게시글 작성 멤버 프로필 조회, 댓글 작성 멤버 프로필 조회, 모임 멤버 리스트 조회에서 상세 조회
- 기존 사용되던 API : 멤버 프로필 상세 조회
- 새로 추가된 API : 특정 모임 멤버 프로필 상세 조회

모임 프로필 플로우 정리
- 각 모임 프로필에서 생년월일, 거주지역, 성별 표시 유무 선택 가능 (기본 프로필에서 제공안함으로 선택했었다면, 모임 프로필에서는 제공안함이 기본으로 선택됨)
- 각 모임 프로필에서 닉네임, 이미지, 자기소개 수정 및 설정 가능

엔티티 수정
- [ ] UserProfile 엔티티 삭제 -> 모든 로직에서 UserProfile 관련된 부분 제거 후 진행
- [x] User 엔티티 필드 추가
- name, imageUrl, introduction
- [x] UserMoim 엔티티 필드 추가
- nickname, imageUrl, introduction, genderVisibility, residenceVisibility
- VisibilityStatus enum 추가

API 추가
- [ ] 특정 모임에서의 유저 프로필 조회 API (로그인한 유저)
- [ ] 특정 모임에서의 다른 멤버 프로필 조회 API
- [ ] 특정 모임에서의 유저 프로필 수정 API 구현

## 👀 ETC
- Todo, Plan 엔티티 UserMoim과 연결로 변경 고려 (현재 User)
- updateUserTodoStatus 실행 시, 쿼리 확인 (findByUserMoimIdAndTodoId)
- [ ] User 테이블 컬럼 추가 서버 DB 반영
- [ ] UserMoim 테이블 컬럼 추가 서버 DB 반영
