### ISSUE TITLE
✨ [Feat] 모임 관리 관련 api 추가

### ISSUE THREAD

**Issue by catturtle123** [M0IM/BE#91]
## 📝 개요
- 모임 관리 관련 api 추가

## ✔️ To-Do
- [x] 모임 가입 신청 상태 확인하기
- [x] 모임 멤버 
- [x] 모임 소개 영상
- [x] 모임 가입하기
- [x] 멤버 권한 수정하기
- [x] 가입 관리하기
- [x] 모임에 신청한 멤버 확인하기

## 👀 ETC
- 참고자료 등 기타 내용 작성
